name: pokedex
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  mocktail: ^0.3.0
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  stringr: ^1.0.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: '#3558cd'
  image: 'assets/splash_image.png'
  android_12:
    image: 'assets/splash_image.png'
    color: '#3558cd'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pokeball.png"